# Generated by Django 2.2.3 on 2019-11-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_menber_ip',
            name='contact',
        ),
        migrations.DeleteModel(
            name='m_menber',
        ),
        migrations.DeleteModel(
            name='m_menber_ip',
        ),
    ]
