# Generated by Django 2.2.3 on 2020-01-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='m_menber_upload',
        ),
    ]
