# Generated by Django 2.2.3 on 2020-01-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_delete_m_menber_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_menber_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0, help_text='绑定的用户ID')),
                ('file', models.CharField(default=0, help_text='上传的文件路径', max_length=250)),
                ('md5', models.CharField(default=0, help_text='计算得出的文件MD5', max_length=250, unique=True)),
                ('type', models.IntegerField(default=0, help_text='1：身份证图片上传 2：其它图片上传 3：头像上传 4：原图上传 5：压缩文件上传 6：文档上传（ppt、word等） 7：源文件 8：视频文件')),
                ('title', models.CharField(default=0, help_text='文件标题', max_length=250)),
                ('file_suffix', models.CharField(default=0, help_text='文件后缀', max_length=250)),
                ('is_scale', models.IntegerField(default=1, help_text='上传时候是否有缩略图 1：有 2：无')),
                ('scale', models.CharField(default='', help_text='缩略图', max_length=250)),
                ('is_auth', models.IntegerField(default=2, help_text='是否释放上传单次限制 1：释放 2：冻结')),
                ('remarks', models.TextField(default='', help_text='备注')),
                ('keyword', models.TextField(default='', help_text='关键词')),
                ('create_time', models.IntegerField(default=1571453334, help_text='创建时间')),
            ],
        ),
    ]
