# Generated by Django 2.2.3 on 2019-11-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20191101_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_c_project',
            name='title',
            field=models.CharField(help_text='小类别名称', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='m_f_project',
            name='title',
            field=models.CharField(help_text='大类别名称', max_length=80, unique=True),
        ),
    ]
