# Generated by Django 2.2.3 on 2019-11-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20191101_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_c_project',
            name='url',
            field=models.CharField(default=0, help_text='采集地址', max_length=100),
        ),
        migrations.AddField(
            model_name='m_f_project',
            name='url',
            field=models.CharField(default=0, help_text='采集地址', max_length=100),
        ),
    ]
