# Generated by Django 2.2.3 on 2020-01-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_m_menber_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_menber_upload',
            name='c_type',
            field=models.CharField(default='', help_text='类型', max_length=250),
        ),
    ]
