# Generated by Django 2.2.3 on 2020-01-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_m_menber_upload_c_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_menber_upload',
            name='mine',
            field=models.CharField(default='', help_text='文件类型', max_length=250),
        ),
        migrations.AddField(
            model_name='m_menber_upload',
            name='size',
            field=models.CharField(default='', help_text='尺寸', max_length=250),
        ),
    ]
