# Generated by Django 2.2.3 on 2020-01-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20200115_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_menber_upload',
            name='error',
            field=models.CharField(default='', help_text='错误提示', max_length=250),
        ),
        migrations.AlterField(
            model_name='m_menber_upload',
            name='is_auth',
            field=models.IntegerField(default=2, help_text='是否释放上传单次限制 1：释放（通过审核） 2：冻结(待审核，占用上传次数) 3:审核失败'),
        ),
    ]
