# Generated by Django 2.2.3 on 2019-11-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_m_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_project',
            name='color_type',
            field=models.CharField(default=0, help_text='素材颜色模式', max_length=50),
        ),
        migrations.AlterField(
            model_name='m_project',
            name='down_png',
            field=models.CharField(default=0, help_text='png文件路径', max_length=600),
        ),
        migrations.AlterField(
            model_name='m_project',
            name='down_zip',
            field=models.CharField(default=0, help_text='压缩文件路径', max_length=600),
        ),
        migrations.AlterField(
            model_name='m_project',
            name='file_type',
            field=models.CharField(default=0, help_text='素材文件格式', max_length=50),
        ),
        migrations.AlterField(
            model_name='m_project',
            name='share',
            field=models.CharField(default=0, help_text='分享者', max_length=50),
        ),
        migrations.AlterField(
            model_name='m_project',
            name='size',
            field=models.CharField(default=0, help_text='素材尺寸', max_length=50),
        ),
    ]
