# Generated by Django 2.2.3 on 2019-11-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_m_contents_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_page_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='地址', max_length=100, unique=True)),
                ('create_time', models.IntegerField(default=1571453334, help_text='创建时间')),
            ],
        ),
    ]
