# Generated by Django 2.2.6 on 2019-11-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_m_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_project',
            name='scale',
            field=models.CharField(default=0, help_text='缩略图', max_length=100),
        ),
    ]
