# Generated by Django 2.2.3 on 2019-11-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0010_m_project_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_page_url',
            name='use',
            field=models.IntegerField(default=0, help_text='爬取状态'),
        ),
    ]
