# Generated by Django 2.2.3 on 2019-11-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0011_m_page_url_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.TextField(default=0, help_text='cookie')),
                ('create_time', models.IntegerField(default=1571453334, help_text='创建时间')),
            ],
        ),
        migrations.DeleteModel(
            name='m_contents_url',
        ),
        migrations.AddField(
            model_name='m_project',
            name='img_view',
            field=models.CharField(default=0, help_text='图片预览', max_length=50),
        ),
    ]
