# Generated by Django 2.2.3 on 2019-11-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0012_auto_20191128_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_l', models.CharField(help_text='标题组合一', max_length=80)),
                ('title_r', models.CharField(help_text='标题组合二', max_length=80)),
                ('contact', models.IntegerField(default=0, help_text='链接ID')),
                ('update_time', models.IntegerField(default=1571453334, help_text='更新时间')),
                ('create_time', models.IntegerField(default=1571453334, help_text='创建时间')),
            ],
        ),
    ]
