# Generated by Django 2.2.3 on 2019-12-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0013_m_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_f', models.CharField(help_text='首推关键词一', max_length=80)),
                ('title_c', models.CharField(help_text='首推关键词二', max_length=80)),
                ('contact_id', models.IntegerField(default=0, help_text='链接ID')),
                ('create_time', models.IntegerField(default=1571453334, help_text='创建时间')),
            ],
        ),
        migrations.DeleteModel(
            name='m_menu',
        ),
    ]
