# Generated by Django 2.2.3 on 2019-12-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0014_auto_20191204_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_navbar',
            name='contact_type',
            field=models.IntegerField(default=0, help_text='链接级别 1：一级； 2：二级'),
        ),
    ]
