# Generated by Django 2.2.3 on 2019-12-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0015_m_navbar_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.IntegerField(default=1571453334, help_text='创建时间')),
                ('path', models.CharField(help_text='json存储位置', max_length=80)),
                ('title', models.CharField(help_text='缓存标识', max_length=80, unique=True)),
            ],
        ),
    ]
